### ISSUE TITLE
Error fixing "Translate id method to python"

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#100]
[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/deep-foundation/deepclient/actions/runs/4908773167)

AutoPR encountered an error while trying to fix https://github.com/deep-foundation/deepclient/issues/23.

## Traceback

```
No traceback
```

While it is visible that GPT-4 got actual translation of the code from the issue. AutoPR didn't made required changes in the file.

**Comment by irgolic** [comment]
This is a pretty weird bug, there've been lots of improvements since you ran this. Could you rerun it? We should get an informative error message at the least.
