### ISSUE TITLE
ValueError: Error looking at files

### ISSUE THREAD

**Issue by vbandi** [irgolic/AutoPR#101]
Unfortunately, it seems like I can't use AutoPR. Even simple requests return with this error. (This is a private repo).

[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/vbandi/<redacted>)

AutoPR encountered an error while trying to fix https://github.com/vbandi/<redacted>

## Traceback

```
Traceback (most recent call last):
  File "/app/autopr/agents/brain_agent/base.py", line 75, in generate_pr
    self._generate_pr(event)
  File "/app/autopr/agents/brain_agent/simple_v1.py", line 27, in _generate_pr
    pr_desc = self.pull_request_agent.plan_pull_request(self.repo, issue, event)
  File "/app/autopr/agents/pull_request_agent/base.py", line 50, in plan_pull_request
    pull_request = self._plan_pull_request(repo, issue, event)
  File "/app/autopr/agents/pull_request_agent/rail_v1.py", line 413, in _plan_pull_request
    notes = self.write_notes_about_files(files, issue, filepaths)
  File "/app/autopr/agents/pull_request_agent/rail_v1.py", line 339, in write_notes_about_files
    raise ValueError('Error looking at files')
ValueError: Error looking at files

```

**Comment by irgolic** [comment]
Hi, sorry for the late reply on this.

There's not enough information for me to be able to discern what went wrong. I'd be interested to see the error; if you're comfortable sharing logs privately, please forward them to hello@irgolic.com.

AutoPR just underwent a pretty big refactor, try it again if you'd like, it might behave differently.

**Comment by vbandi** [comment]
@irgolic thank you for the answer. I'm happy to test the post-refactor AutoPR. But I'm new to Github actions... how do I make sure I use the latest version?

Thanks!

**Comment by irgolic** [comment]
If your workflow file says:

```yaml
    - name: AutoPR
      uses: docker://ghcr.io/irgolic/autopr:latest
```

Then you're using the latest version (main branch).

**Comment by vbandi** [comment]
Thank you - I've been using the latest version according to this. I've sent you the log privately.

**Comment by irgolic** [comment]
Hey, I've submitted a PR that should hopefully fix the issue. It happened because there's so many files in the repo. This is more of a hotfix, the proper solution will use semantic embeddings instead of showing the LLM a list of filepaths.

Could you try it out? In your workflow file, put:

```yaml
    - name: AutoPR
      uses: irgolic/autopr@fallback-plan-pr-param-trim
```

**Comment by vbandi** [comment]
Hi @irgolic ... Thank you. I've managed have an error-free run, but it created a PR with 3 commits and 0 changed files.

![image](https://github.com/irgolic/AutoPR/assets/1344888/5bdd328f-18f9-4ebf-8b46-fcfdebefd150)

**Comment by irgolic** [comment]
Hi, sorry for the wait.

What you're seeing with the deep nesting of "Editing file" is a weird bug; I've now overhauled the progress reporting system, so it hopefully shouldn't happen again. 

Could you try again, on the same `fallback-plan-pr-param-trim` branch? This time it'll hopefully be clearer what it's getting stuck on, if you'll look at the prompts/responses where it says "Failed to edit file". 

Finding this bug has been a massive help, it relates to there being too many files to fit in the prompt, and trimming them properly (although still naively). AutoPR is not yet optimized for big repositories, so thanks a lot for trying it out.

**Comment by irgolic** [comment]
Cool, could you show some of its reasoning? What was the plan it made given the issue?

**Comment by vbandi** [comment]
Would it be possible to limit the files AutoPR is working on? The repo in question is a kind of internal playground project of mine, and consists of a ton of files generated by Unity and other tools. I think that's the reason it didn't find the right file to work on. The actual task only requires understanding a handful of files, maybe even just one. 

AutoPR took 13 minutes to process the repo, but it'd be great to be able to limit it to a smaller set of files - just like I'd point a junior dev on my team to the right place to look for a task like this.

**Comment by irgolic** [comment]
You can put a `.gptignore` file in the root of the repo, works like a `.gitignore`.

Alternatively, you could specify some filepaths in the issue, I've found it to pick up on that pretty well

**Comment by vbandi** [comment]
OK, now we're cooking! I limited the folders to the one project I'm interested in (still a few dozen files), and it found the right file and made some modifications that actually had something to do with what I needed. Thank you!

**Comment by irgolic** [comment]
I'm so glad to hear that, thanks for testing and sticking with it. 

If you need anything else, please don't hesitate to reach out.
