### ISSUE TITLE
How to know if OpenAI key is valid?

### ISSUE THREAD

**Issue by cquanu** [irgolic/AutoPR#110]

**Comment by irgolic** [comment]
Hey, thanks for dropping in. Sorry I don't understand your question.

At the moment you need your own OpenAI key to use AutoPR.

Feel free to reopen the issue if you have a followup question.

**Comment by cquanu** [comment]
Sorry, I meant how to know if AutoPR is working? I got Error decoding file error on the GitHub actions log. So I’m wondering if it’s OpenAI key invalid or something else.
