### ISSUE TITLE
OpenAI error

### ISSUE THREAD

**Issue by krrishdholakia** [irgolic/AutoPR#115]
Hey @irgolic, 

Facing openai context window limit errors. 

Would recommend wrapping the openai completion base with `reliableGPT` to handle retries, model switching, etc. 

```
from reliablegpt import reliableGPT
openai.ChatCompletion.create = reliableGPT(openai.ChatCompletion.create, user_email=...)
```

Source: https://github.com/BerriAI/reliableGPT

**Comment by irgolic** [comment]
Hi @krrishdholakia, thanks for reaching out.

I use tenacity to handle retries, unsure how this is useful apart from rotating API keys, or why a user email is needed.
