### ISSUE TITLE
Empty commit with [placeholder] title

### ISSUE THREAD

**Issue by WezSieTato** [irgolic/AutoPR#122]
Hi. 
I wanna use AutoPR to automate translations in my project. I followed with documentation and added proper workflow and secret.
Then I created a small issue with a plain description (I think :) ). AutoPR workflow ran and finished with success but no PR was created. The only output of this action was an empty commit with a "[placeholder]" title.

Link to labelled issue: https://github.com/WezSieTato/ScanNow/issues/63

**Comment by irgolic** [comment]
Hey, sorry for the delay, I'm assuming you're trying to use the initial functionality of AutoPR (generating an pull request from an issue). Could you try replacing line 40 in your `autopr.yml` file?

From:
```yaml
      uses: irgolic/AutoPR@main
```
to
```yaml
      uses: docker://ghcr.io/irgolic/autopr:v0.1.2
```

**Comment by NiftyOctopus** [comment]
@irgolic Has this functionality (generating PR from issue) been depreciated permanently?

**Comment by irgolic** [comment]
Not permanently, but we're moving toward a configurable infrastructure for writing LLM-powered processes over your git repo. We're hitting some lower-hanging fruit first, and will be reimplementing generating PR from issues in a way that allows configuring different generation use cases.

To be honest, I wasn't expecting so many people to be using AutoPR's issue => PR generation, lots popped their heads out after I made the change to main. Is there something you found it better at than the alternatives (namely Sweep)?

**Comment by WezSieTato** [comment]
Thanks, it helped :) It created one PR and now I have another problem connected with PR creation. I understood that creating issues connected with the old version (with issue->PR feature) doesn't make sense :D 

For me, this feature is great for non-code issues like translations or content creation. I will check Sweep but I prefer solutions where I use my own API key for openai like this.

**Comment by irgolic** [comment]
Awesome, thanks for the insight. I'll keep your use case in mind, I think we should be able to support something like that in a more structured way quite soon.
