### ISSUE TITLE
Got `Poetry could not find a pyproject.toml file in /github/workspace or its parents` in a non-Python project

### ISSUE THREAD

**Issue by dhnaranjo** [irgolic/AutoPR#13]
Heywhattup, I tried using this on a new Ruby on Rails project, just for play, and the workflow failed when invoking the action with: `Poetry could not find a pyproject.toml file in /github/workspace or its parents`. Does this action only intend to support Python projects?

**Comment by dhnaranjo** [comment]
It does appear to work now, tho now I am blocked by not having gpt-4 api access. Oh well. Let's see if I get thru that waitlist.

**Comment by irgolic** [comment]
I've pushed a commit that [lets you change the model](https://github.com/irgolic/AutoPR/blob/main/.github/workflows/create-pr-from-issue.yml#L41).

Try setting `model` to `gpt-3.5-turbo` (as well as `context_limit` to `4096`), let me know how it works.
