### ISSUE TITLE
Update CONTRIBUTING doc to mention opening issues to create PRs

### ISSUE THREAD

**Issue by sparr** [irgolic/AutoPR#22]
`CONTRIBUTING.md` describes how a human developer can write code to improve this project. It neglects to mention that this repository runs itself on new issues (such as this one) which will trigger the creation of a PR attempting to implement the request or idea in the issue. Add a section to `CONTRIBUTING.md` explaining that opening an issue is a viable way to contribute.

**Comment by sparr** [comment]
https://github.com/irgolic/AutoPR/actions/runs/4547989745/jobs/8018546966

> Issue not created by a collaborator. Skipping action.

**Comment by irgolic** [comment]
Hey, you're right, this should totally be a thing. The problem is that it's rather expensive to run, so I'd prefer to have a manual trigger for non-contributors.

I thought I could manually trigger an issue someone else created if I edited it, but seems like that's not the case. I'll look into it.

**Comment by irgolic** [comment]
Now that we've got a manual trigger, let's try. 🚀

**Comment by irgolic** [comment]
Now that we've got a manual trigger, let's try. 🚀

**Comment by siwatanejo** [comment]
> The problem is that it's rather expensive to run

What do you mean with expensive? I thought Plus was a flat fee (assuming you're running Plus).

**Comment by irgolic** [comment]
> > The problem is that it's rather expensive to run
> 
> What do you mean with expensive? I thought Plus was a flat fee (assuming you're running Plus).

Sorry I didn't notice this comment earlier @siwatanejo. ChatGPT Plus is flat fee, but GPT-4 API is charged per call.
