### ISSUE TITLE
🚀 Add docstrings

### ISSUE THREAD

**Issue by dmarx** [irgolic/AutoPR#34]
This is a maturing codebase which unsurprisingly doesn't have a lot of documentation yet. Since potential collaborators will need to examine the code to understand how things work, it would be helpful if the code was self-documented. docstrings are an excellent way to achieve this. additionally, building API documentation with sphinx can then be incorporated into the CI/CD with github actions. Would also be nice if the README added a section demonstrating how to customize behavior, e.g. modifying prompts or configuring additional triggers.

**Comment by irgolic** [comment]
Regardless of whether AutoPR is able to fix this or not, it's an important issue.
