### ISSUE TITLE
Include repo owner in collaborator check

### ISSUE THREAD

**Issue by Eddydpyl** [irgolic/AutoPR#39]
In the "Check if issue or issue comment is created by collaborator or repo owner" step in `create-pr-from-issue.yml`, we should explicitly check for the repo owner, and allow issues coming from them to trigger the workflow.

**Comment by irgolic** [comment]
I thought repo owners also counted as collaborators 🤔 Or do you mean to only allow the repo owner to trigger, not any collaborator?
Now that https://github.com/irgolic/AutoPR/pull/38 has been merged (triggering PRs with label instead of rocket comment), are you still experiencing this issue?

**Comment by Eddydpyl** [comment]
I had to add the check in my repo for it to recognize me. I'll try again.

**Comment by Eddydpyl** [comment]
Sorry for the delay, tried again and all works as expected, closing.

**Comment by irgolic** [comment]
No worries, thanks for letting me know!
