### ISSUE TITLE
Towards an autonomous PR planner

### ISSUE THREAD

**Issue by irgolic** [irgolic/AutoPR#55]
Some thoughts on what an improved pull request planning agent might look like, and how to implement it.

There should be another `repo` called `EmbeddingsRepo`, that stores embedded texts and searches among them. It should allow multiple implementations under the same interface:
- storing the embeddings in a file in the repo (preferably not pickle, which can execute arbitrary code at unpickle-time), loading them all into memory and computing cosine distance over the vectors
- using a vector database provider like Pinecone, wherein the distance calculation is done in a separate abstraction layer

The files in the repo should be summarized, the summary embedded and cached by the `EmbeddingsRepo`. This should be triggerable either:
- by a separate github workflow (i.e., on main push, any changed files are recomputed)
- at the start of the AutoPR run, before giving the `brain_agent` control

Then, an autonomous version of a `pull_request_agent` should be implemented; its action set should be:
- semantic query over repo, searching through file summary embeddings
- Ctrl+Shift+F style global find query, allowing it to control context window (default ~10 lines)
- plan a commit
- finish (after a commit has been planned)

**Comment by sionsmith** [comment]
Following this thread, would the idea be to be basically store the embeddings for each repo? So that there is a summary available of each repo or file?
