### ISSUE TITLE
Error fixing "Write a discord bot to assist in conversations"

### ISSUE THREAD

**Issue by bluewin4** [irgolic/AutoPR#57]
[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/bluewin4/angleNdevil/actions/runs/4780362177)

AutoPR encountered an error while trying to fix https://github.com/bluewin4/angleNdevil/issues/2.

**Comment by irgolic** [comment]
Hey, thanks for clicking the "open an issue" link.

The repository's private, could you share access to me, or make it public?

**Comment by irgolic** [comment]
This ended up being a parsing bug thrown from within guardrails, now circumvented by using their instruction prompts.
