### ISSUE TITLE
ValueError: Error looking at files

### ISSUE THREAD

**Issue by tsnieman** [irgolic/AutoPR#72]
# generated output

![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)

AutoPR encountered an error while trying to fix (redacted repo/issue).

## Traceback

```
Traceback (most recent call last):
  File "/app/autopr/agents/brain_agent/base.py", line 75, in generate_pr
    self._generate_pr(event)
  File "/app/autopr/agents/brain_agent/simple_v1.py", line 27, in _generate_pr
    pr_desc = self.pull_request_agent.plan_pull_request(self.repo, issue, event)
  File "/app/autopr/agents/pull_request_agent/base.py", line 50, in plan_pull_request
    pull_request = self._plan_pull_request(repo, issue, event)
  File "/app/autopr/agents/pull_request_agent/rail_v1.py", line 392, in _plan_pull_request
    notes = self.write_notes_about_files(files, issue, filepaths)
  File "/app/autopr/agents/pull_request_agent/rail_v1.py", line 317, in write_notes_about_files
    raise ValueError('Error looking at files')
ValueError: Error looking at files

```

# more context:
The issue was something like:
```
in path/to/file.tsx, update the "messages" and "files" Buttons to be IconButtons. also add aria-label properties to them.
```

The action's log seemed to output a ton of activity, but it said it failed before the action had even finished with the message above in the generated PR. Not sure why it failed.

**Comment by irgolic** [comment]
Hey, thanks for reporting this.

That's an interesting error, I think I'd need to see the prompt and response to debug it. If you'd be comfortable sharing them privately, feel free to message me on Discord or email me at hello@irgolic.com.

Though to be honest, I'm planning to rewrite the pull request agent in the next few days. You could just try running it again when I publish the new agent.
