### ISSUE TITLE
Error fixing "Remove duplicate hello_world.rs from root of repository as it already exists at src/hello_world.rs"

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#80]
[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/Konard/AutoPR-tests/actions/runs/4887159971)

AutoPR encountered an error while trying to fix https://github.com/Konard/AutoPR-tests/issues/13.

## Traceback

```
No traceback
```

File is not removed from the root of repository.

**Comment by Konard** [comment]
The actual problem is here https://github.com/irgolic/AutoPR/issues/81

**Comment by irgolic** [comment]
Closed as duplicate of #81
