### ISSUE TITLE
TDD by default

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#85]
It would be much easier for AI to solve bugs or add new features, it will always add tests before any attempts to do a solution.
Tests approval is mandatory and should be implemented as part of https://github.com/irgolic/AutoPR/issues/31
Without strict definition toward the goal, no goals are achievable.
And only tests can clear state what the goal is.

Tests could also be used to test hypotheses if there are many options to choose from. Related to https://github.com/irgolic/AutoPR/issues/93

**Comment by irgolic** [comment]
I agree, it's going to be a lot more powerful when it runs tests and iterates the PR over failed test runs.

One way to test this right now is to run tests manually and post the results as an issue comment containing "hey autopr". Though getting this built-in is high priority.
