### ISSUE TITLE
Every step should be approved by default

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#87]
For example repository file structure change, public api change, change in the file an so on.
That would require https://github.com/irgolic/AutoPR/issues/31

**Comment by irgolic** [comment]
From my understanding, you're saying each conceptual change should be approved.

As an alternative to this... If an issue is unclear, and its file search doesn't yield anything good, it'll ask for more information. So I'm closing this for now.

If you'd like to propose an alternative, see [how the RequestMoreInformation action is implemented](https://github.com/irgolic/autopr/blob/6eff8798a152d5cb9ecddd2d6f499dca8e9be73b/autopr/actions/request_more_info.py#L5). Perhaps you could define a new similar action that makes it stop and ask for approval when it plans to do something not explicitly outlined in the issue.
