### ISSUE TITLE
Issue content alongside with comments should be summarized

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#88]
I think it is not required for AutoPR to participate in debates, at least at the moment.
Anyway, any feedback from users in issues should be summarized due to limits. All points of view should be collected and weighted. If any questions arise, it should ask them in pull request, or later it may participate in debates in issues when it will be so autonomous that it will select best issues it can tackle first and clear all confusion in the process of understanding the task.

Related to https://github.com/irgolic/AutoPR/issues/31 and https://github.com/irgolic/AutoPR/issues/93

**Comment by irgolic** [comment]
There are a couple points raised in this issue.

I've only been working with relatively small issues so far, so summarizing it hasn't come up on my radar. It already gets encoded while looking at files, when compiling the plan for the pull request. Are you trying to run it on really long issues?

If you're talking about it picking issues by itself, I've only explored user-triggered generation so far. It would be cool to have it crawl a repository to find issues it would feel confident fixing, but I can't think of a reliable way of doing this yet.
