### ISSUE TITLE
Level of how autonomous the AutoPR is should be highly configurable

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#89]
There may be repository level configurations with a range or select action to do automatically.
There also may be issue level configuration, by default the same as for repository.
And the default level for repository should be set to allow zero configuration for users. Do autonomously only things it is good at.

**Comment by irgolic** [comment]
AutoPR is currently configurable in that you can adjust which actions run as part of a triggered workflow. 

Perhaps what you're looking for is a more direct way of interacting with GPT-4 in a PR? As in, one GPT-4 call per AutoPR run? We could implement something like that as a separate agent. If that's the case, please open a separate issue for that.
