### ISSUE TITLE
Use CodeQL or grep search for potential affected places in code across repository

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#91]
This will dramatically reduce the number of requests to GPT-4 directly for huge projects. 
Or maybe it should be also guided by user to look at specific places as in https://github.com/irgolic/AutoPR/issues/31

Or maybe we should build the graph of code with all implicit and explicit dependencies, including monkey patches and so on. And the moonshot idea - to see how users use the code in other repositories.

Related to: https://github.com/irgolic/AutoPR/issues/90

**Comment by Konard** [comment]
The idea for code graph is updated it each time files in the repository are changed.
The graph should have links that define which function/code block depends on which other code block/function/field. The simple select query will directly give an answer that code should be investigated before making a change. In this query, we also will be able to directly get relevant code parts.
For storing the code graph I recommend to use associative storage from Deep as in https://deep.foundation

**Comment by irgolic** [comment]
Right now it only operates over filenames, so better context gathering from something akin to a code graph will improve it a lot. It'd be great to include the ability to query context from the code graph during both the planning and code writing stages.

Things to check out:
- https://lsif.dev/
- https://about.sourcegraph.com/blog/announcing-scip
