### ISSUE TITLE
Error fixing "TypeError: 'NoneType' object is not a mapping in select method of DeepClient"

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#98]
[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/deep-foundation/deepclient/actions/runs/4907995972)

AutoPR encountered an error while trying to fix https://github.com/deep-foundation/deepclient/issues/19.

## Traceback

```
No traceback
```

Instead of making changes in existing files AutoPR just created new files.

**Comment by irgolic** [comment]
Here it runs into a similar issue to #99, I'll close this issue as a duplicate.
