### ISSUE TITLE
Error fixing "Error in test_select"

### ISSUE THREAD

**Issue by Konard** [irgolic/AutoPR#99]
[![AutoPR Failure](https://img.shields.io/badge/AutoPR-failure-red)](https://github.com/deep-foundation/deepclient/actions/runs/4908068346)

AutoPR encountered an error while trying to fix https://github.com/deep-foundation/deepclient/issues/21.

## Traceback

```
No traceback
```

AutoPR didn't make changes in original files.
However, the code it generated contained a fix.

**Comment by irgolic** [comment]
Seems like at some point when looking through the files, it fumbled the `python/deepclient/deep_client.py` path by dropping the `python` directory. I think a good way to fix this would be to give it more guidance on what kind of notes to take, telling it to specify exact filepaths.

Specifically, prompt engineering to be done in these two places:
- https://github.com/irgolic/autopr/blob/6eff8798a152d5cb9ecddd2d6f499dca8e9be73b/autopr/actions/look_at_files.py#L146
- https://github.com/irgolic/autopr/blob/6eff8798a152d5cb9ecddd2d6f499dca8e9be73b/autopr/actions/look_at_files.py#L201
